# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureravailability',
            old_name='lecture',
            new_name='lecturer',
        ),
        migrations.AlterField(
            model_name='lectureravailability',
            name='day',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
